[pytest]
addopts = -v -p no:cacheprovider --html=reports/report.html --self-contained-html
testpaths = tests
markers =
    ui: pruebas de interfaz web con Selenium
    api: pruebas de servicios API con Requests
